# Generated by Django 5.2.7 on 2026-01-18 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='nombre',
            field=models.CharField(max_length=45, verbose_name='Nombre'),
        ),
    ]
