# Generated by Django 5.2.6 on 2025-09-28 22:07

import django.db.models.deletion
import operaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comunidad', '0005_alter_usuario_imagen_tienda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, default='operaciones/productos/default-producto.png', null=True, upload_to=operaciones.models.get_image_filename)),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('precio', models.PositiveIntegerField(verbose_name='Precio')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('estado', models.BooleanField(default=True)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunidad.tienda', verbose_name='Tienda')),
            ],
        ),
    ]
