# Generated by Django 5.2.6 on 2025-10-02 19:04

import operaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='operaciones/productos/default.producto.png', null=True, upload_to=operaciones.models.get_image_filename),
        ),
    ]
