# Generated by Django 5.2.6 on 2025-09-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=45, verbose_name='Primer Nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=45, null=True, verbose_name='Segundo Nombre')),
                ('primer_apellido', models.CharField(max_length=45, verbose_name='Primer Apellido')),
                ('segundo_apellido', models.CharField(max_length=45, verbose_name='Segundo Apellido')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('rol', models.CharField(choices=[('AD', 'Administrador'), ('CL', 'Cliente'), ('EM', 'Empleado')], default='CL', max_length=2, verbose_name='Rol')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula'), ('CE', 'Cédula de Extrangería')], max_length=2, verbose_name='Tipo de Documento')),
                ('documento', models.PositiveIntegerField(unique=True, verbose_name='Documento')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
