# Generated by Django 5.2.6 on 2025-09-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0003_usuario_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_registro',
            field=models.DateField(verbose_name='Fecha de Registro'),
        ),
    ]
