# Generated by Django 5.2.6 on 2025-09-28 20:30

import comunidad.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0004_alter_usuario_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, default='comunidad/default-user.jpeg', null=True, upload_to=comunidad.models.get_image_filename),
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('nit', models.PositiveIntegerField(unique=True, verbose_name='NIT')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('estado', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunidad.usuario', verbose_name='Administrador')),
            ],
        ),
    ]
