# Generated by Django 5.2.7 on 2025-10-19 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0006_remove_usuario_email_usuario_correo_usuario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
    ]
